[package]
name = "sshping"
version = "0.1.5"
edition = "2021"
description = "SSH-based ping that measures interactive character echo latency and file transfer throughput. Pronounced \"shipping\"."
authors = ["Nan Huang <teddyhuangnan@gmail.com>"]
license = "MIT"

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.5.7", features = [
  "derive",
  "string",
  "cargo",
  "color",
  "wrap_help",
] }
clap_complete = "4.5.38"
humantime = "2.1.0"
indicatif = "0.17.8"
log = "0.4.21"
num-format = "0.4.4"
rand = "0.8.5"
shellexpand = "3.1.0"
simple_logger = "5.0.0"
size = "0.4.1"
ssh2 = "0.9.4"
ssh2-config = "0.3.0"
tabled = "0.17.0"
whoami = "1.5.1"

[features]
default = []
include-openssl = ["ssh2/vendored-openssl"]
