[package]
name = "sshping"
version = "0.1.0"
edition = "2021"
description = "SSH-based ping that measures interactive character echo latency and file transfer throughput. Pronounced \"shipping\"."
authors = ["Nan Huang <teddyhuangnan@gmail.com>"]

[dependencies]
clap = { version = "4.5.7", features = ["derive", "string", "cargo"] }
log = "0.4.21"
shellexpand = "3.1.0"
simple_logger = "5.0.0"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
ssh2-config = "0.2.3"
users = "0.11.0"
