edition = "2021"
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
unstable_features = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
