# Based on typst's release action:
# https://github.com/typst/typst/blob/main/.github/workflows/release.yml

name: Test Build Binaries
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
    tags-ignore:
      - "**"
  workflow_dispatch:

jobs:
  test-build:
    name: test ${{ matrix.target }}(${{ matrix.feature }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            feature: include-openssl
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            feature: include-openssl
          - target: x86_64-apple-darwin
            os: macos-13
            feature: default
          - target: aarch64-apple-darwin
            os: macos-latest
            feature: default
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            feature: default
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
            feature: default

    steps:
      - uses: actions/checkout@v5

      - name: Install Cross-Compilation Tools
        if: contains(matrix.target, 'linux-musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config libssl-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Run Cargo
        run: cargo build --locked --target ${{ matrix.target }} -F ${{ matrix.feature }}

      # We might include unit test in the future, but we don't have any at the time
